import Head from 'next/head'
import { useGetPatients } from '../../queries/patients'
import { useGetMunicipios } from '../../queries/municipios';

export default function Home() {
  const { data: patients } = useGetPatients();
  const { data: municipios } = useGetMunicipios(); 

  console.log(patients);
  console.log({ municipios });

  return (
    <>
      <Head>
        <title>Expeciente Clínico Electronico Pediátrico</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      </main>
    </>
  )
}
